name: Test

on:
  push:
    branches:
      - master
  pull_request: {}

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    runs-on: ubuntu-20.04
    env:
      RUST_LOG: debug
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: curl -L https://bitcoincore.org/bin/bitcoin-core-22.0/bitcoin-22.0-x86_64-linux-gnu.tar.gz | tar -xvz
      - run: echo "$GITHUB_WORKSPACE/bitcoin-22.0/bin" >> $GITHUB_PATH
      - run: echo "BITCOIND_EXE=$GITHUB_WORKSPACE/bitcoin-22.0/bin/bitcoind" >> $GITHUB_ENV
      - run: curl -L https://github.com/ElementsProject/lightning/releases/download/v0.10.2/clightning-v0.10.2-Ubuntu-20.04.tar.xz | tar -xJ
      - run: echo "$GITHUB_WORKSPACE/usr/bin" >> $GITHUB_PATH
      - run: echo "LIGHTNINGD_EXE=$GITHUB_WORKSPACE/usr/bin/lightningd" >> $GITHUB_ENV
      - run: cargo test

  cosmetics:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - run: cargo fmt -- --check
      - run: cargo clippy -- -D warnings

  rust-version:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        toolchain: [ "1.70.0", "stable", "nightly" ]

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.toolchain }}
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
      - run: cargo build
